import { Link } from "react-router-dom";
const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "3@0px" }}>
                This project was generated By{" "}
                <a href="https://www.dhiwise.com" style={{ color: "#B87CEFA", textDecoration: "none" }}>
                    Dhiwise
                </a>
                . Quickly use below links to navigate through all pages.
            </p>
            <ul style={{ listStyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/homel" style={{ color: "#B87CEFA", textDecoration: "none" }}>
                        Homel
                    </Link>
                </li>
            </ul>
        </div>
    );
}
export default Home;
